let\
    Fonte = Csv.Document(File.Contents("C:\\Users\\claudiomattos\\Documents\\GitHub\\COVID-19\\csse_covid_19_data\\csse_covid_19_time_series\\time_series_19-covid-Confirmed.csv"),[Delimiter=",", Columns=61, Encoding=65001, QuoteStyle=QuoteStyle.None]),\
    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,\{\{"Column1", type text\}, \{"Column2", type text\}, \{"Column3", type text\}, \{"Column4", type text\}, \{"Column5", type text\}, \{"Column6", type text\}, \{"Column7", type text\}, \{"Column8", type text\}, \{"Column9", type text\}, \{"Column10", type text\}, \{"Column11", type text\}, \{"Column12", type text\}, \{"Column13", type text\}, \{"Column14", type text\}, \{"Column15", type text\}, \{"Column16", type text\}, \{"Column17", type text\}, \{"Column18", type text\}, \{"Column19", type text\}, \{"Column20", type text\}, \{"Column21", type text\}, \{"Column22", type text\}, \{"Column23", type text\}, \{"Column24", type text\}, \{"Column25", type text\}, \{"Column26", type text\}, \{"Column27", type text\}, \{"Column28", type text\}, \{"Column29", type text\}, \{"Column30", type text\}, \{"Column31", type text\}, \{"Column32", type text\}, \{"Column33", type text\}, \{"Column34", type text\}, \{"Column35", type text\}, \{"Column36", type text\}, \{"Column37", type text\}, \{"Column38", type text\}, \{"Column39", type text\}, \{"Column40", type text\}, \{"Column41", type text\}, \{"Column42", type text\}, \{"Column43", type text\}, \{"Column44", type text\}, \{"Column45", type text\}, \{"Column46", type text\}, \{"Column47", type text\}, \{"Column48", type text\}, \{"Column49", type text\}, \{"Column50", type text\}, \{"Column51", type text\}, \{"Column52", type text\}, \{"Column53", type text\}, \{"Column54", type text\}, \{"Column55", type text\}, \{"Column56", type text\}, \{"Column57", type text\}, \{"Column58", type text\}, \{"Column59", type text\}, \{"Column60", type text\}, \{"Column61", type text\}\}),\
    #"Cabe\'e7alhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),\
    #"Somente as Colunas Selecionadas Foram Transformadas em Linhas" = Table.Unpivot(#"Cabe\'e7alhos Promovidos", \{"1/22/20", "1/23/20", "1/24/20", "1/25/20", "1/26/20", "1/27/20", "1/28/20", "1/29/20", "1/30/20", "1/31/20", "2/1/20", "2/2/20", "2/3/20", "2/4/20", "2/5/20", "2/6/20", "2/7/20", "2/8/20", "2/9/20", "2/10/20", "2/11/20", "2/12/20", "2/13/20", "2/14/20", "2/15/20", "2/16/20", "2/17/20", "2/18/20", "2/19/20", "2/20/20", "2/21/20", "2/22/20", "2/23/20", "2/24/20", "2/25/20", "2/26/20", "2/27/20", "2/28/20", "2/29/20", "3/1/20", "3/2/20", "3/3/20", "3/4/20", "3/5/20", "3/6/20", "3/7/20", "3/8/20", "3/9/20", "3/10/20", "3/11/20", "3/12/20", "3/13/20", "3/14/20", "3/15/20", "3/16/20", "3/17/20", "3/18/20"\}, "Atributo", "Valor"),\
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Somente as Colunas Selecionadas Foram Transformadas em Linhas",\{\{"Valor", Int64.Type\}\}),\
    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado1", \{\{"Atributo", type date\}\}, "en-US"),\
    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado com Localidade",\{"Lat", "Long", "Atributo", "Valor", "Province/State"\}),\
    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Removidas"),\
    #"Linhas em Branco Removidas" = Table.SelectRows(#"Duplicatas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), \{"", null\})))\
in\
    #"Linhas em Branco Removidas"}
